services:
  prometheus:
    image: prom/prometheus:main-distroless

    ports:
    - 9090:9090

    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - monitoring-net
    # depends_on:
    #   cadvisor:
    #     condition: service_healthy

#####################################################

  grafana:
    image: grafana/grafana:nightly-slim

    ports:
    - 3000:3000

    volumes:
    - grafana-storage:/var/lib/grafana

    networks:
      - monitoring-net

    #logging:
    #  driver: none

    environment:
      GF_SERVER_ROOT_URL: http://localhost/monitor/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    # depends_on:
    #   prometheus:
    #     condition: service_healthy

#####################################################

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true

    ports:
      - "8081:8080"

    networks:
      - monitoring-net

    volumes:
      - /:/rootfs:ro 
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
      - /dev/disk/:/dev/disk:ro 
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    depends_on:
      users-service:
        condition: service_healthy
      chat-service:
        condition: service_healthy
      postgres-users-svc:
        condition: service_healthy
      postgres-chat-svc:
        condition: service_healthy
      front:
        condition: service_healthy
      redis-svc:
        condition: service_healthy
      # celery-users:
      #   condition: service_healthy
      # celery-chat:
      #   condition: service_healthy


#####################################################

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest

    ports:
      - 9113:9113

    networks:
      - monitoring-net
      - front-net

    command: ["--nginx.scrape-uri=http://front:80/stub_status"]

    depends_on:
      front:
        condition: service_healthy

#####################################################

volumes:
  grafana-storage:
