global:
  scrape_interval: 5s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']
