apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
    app: mates
resources:
  - front.yaml
  - users-service/users.yaml
  - users-service/postgres.yaml
  - secrets/users.yml