# Generated by Django 5.2.11 on 2026-05-02 19:55

import Rooms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('private', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='a Mates Room, join us!!', max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('study', 'Study'), ('games', 'Games'), ('programing', 'Programming'), ('life issues', 'Lifeissues'), ('other', 'Other')], default='other', max_length=20)),
                ('room_image', models.ImageField(blank=True, default='main.png', max_length=255, null=True, upload_to=Rooms.models.getroomImageFilepath)),
                ('room_banner', models.ImageField(blank=True, default='main.png', max_length=255, null=True, upload_to=Rooms.models.getroombannerFilepath)),
            ],
        ),
        migrations.CreateModel(
            name='UserSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinDate', models.DateTimeField(auto_now_add=True)),
                ('leftDate', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.usersnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to='Rooms.usersnapshot'),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ManyToManyField(through='Rooms.MemberShip', to='Rooms.usersnapshot'),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('null', 'Null')], default='pending', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.usersnapshot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_room_member'),
        ),
    ]
